from __future__ import annotations

from typing import Any

PRESETS: tuple[dict[str, Any], ...] = (
    {
        "identifier": "counterexample_hungarian",
        "label": "Cáfolat keresése (magyar kérés)",
        "query": "cáfold meg az x/(x-1) = 1 azonosságot",
        "problem_kind": "algebraic_identity_counterassignment",
        "description": "magyar nyelvű cáfolatkérés: pontos ellenpélda a polelkerüléssel",
        "expected": "counterexample",
        "budget": {"time_seconds": 20, "max_frontier_visits": 60, "execution_timeout_seconds": 8},
    },
    {
        "identifier": "algebraic_pole_refutation",
        "label": "Identity with pole exclusions",
        "query": "refute the identity x/(x-1) = 1",
        "problem_kind": "algebraic_identity_counterassignment",
        "description": "an exact counterassignment that avoids the pole of the left hand side",
        "expected": "counterexample",
        "budget": {"time_seconds": 20, "max_frontier_visits": 60, "execution_timeout_seconds": 8},
    },
    {
        "identifier": "algebraic_polynomial_refutation",
        "label": "Polynomial identity refutation",
        "query": "find a counterexample for x^2 + 1 = x^2",
        "problem_kind": "algebraic_identity_counterassignment",
        "description": "a polynomial identity that fails over the rationals",
        "expected": "counterexample",
        "budget": {"time_seconds": 20, "max_frontier_visits": 60, "execution_timeout_seconds": 8},
    },
    {
        "identifier": "constrained_integer_assignment",
        "label": "Constrained integer assignment",
        "query": "for all nonnegative integers n, n + 1 = n",
        "problem_kind": "algebraic_identity_counterassignment",
        "description": "the candidate assignment must respect the declared integer and sign constraints",
        "expected": "counterexample",
        "budget": {"time_seconds": 20, "max_frontier_visits": 60, "execution_timeout_seconds": 8},
    },
    {
        "identifier": "symbolic_identity_proof",
        "label": "Symbolically true identity",
        "query": "prove that sin(x)^2 + cos(x)^2 = 1 for every real x",
        "problem_kind": "algebraic_identity_counterassignment",
        "description": "the engine proves the identity symbolically and reports no counterassignment",
        "expected": "symbolic_proof",
        "budget": {"time_seconds": 20, "max_frontier_visits": 60, "execution_timeout_seconds": 8},
    },
    {
        "identifier": "finite_group_square",
        "label": "Finite group countermodel",
        "query": "In every finite group, x^2 = e",
        "problem_kind": "finite_group_identity_countermodel",
        "description": "a complete operation table that violates the claimed law",
        "expected": "counterexample",
        "budget": {"time_seconds": 20, "max_frontier_visits": 120, "execution_timeout_seconds": 12, "max_group_order": 6},
    },
    {
        "identifier": "finite_group_commuting",
        "label": "Nonabelian group countermodel",
        "query": "In every finite group of order at most 8, x*y = y*x",
        "problem_kind": "finite_group_identity_countermodel",
        "description": "a nonabelian group within the declared order bound",
        "expected": "counterexample",
        "budget": {"time_seconds": 25, "max_frontier_visits": 160, "execution_timeout_seconds": 15, "max_group_order": 8},
    },
    {
        "identifier": "jacobi_finite_field_refutation",
        "label": "Jacobi-sejtés cáfolata (véges test)",
        "query": "cáfold meg a 2D Jacobi-sejtést",
        "problem_kind": "finite_field_jacobian_refutation",
        "description": "véges testek fölött exact keresés konstans nemzérus Jacobi-determinánsú, nem injektív polinom leképezésre",
        "expected": "counterexample",
        "budget": {"time_seconds": 25, "max_frontier_visits": 40, "execution_timeout_seconds": 12},
    },
    {
        "identifier": "jacobi_finite_field_refutation_english",
        "label": "Jacobi conjecture refutation over finite fields",
        "query": "refute the two dimensional Jacobian conjecture over a finite field",
        "problem_kind": "finite_field_jacobian_refutation",
        "description": "exact collision search over GF(p^k) for a polynomial map with constant nonzero Jacobian determinant",
        "expected": "counterexample",
        "budget": {"time_seconds": 25, "max_frontier_visits": 40, "execution_timeout_seconds": 12},
    },
    {
        "identifier": "planar_jacobian_characteristic_zero",
        "label": "Jacobi conjecture in characteristic zero (open)",
        "query": "refute the two dimensional Jacobian conjecture over the rationals",
        "problem_kind": "planar_constant_determinant_collision",
        "description": "the characteristic zero case is open: the search reports an honest exhaustion instead of a counterexample",
        "expected": "exhaustion",
        "budget": {"time_seconds": 25, "max_frontier_visits": 24, "execution_timeout_seconds": 10},
    },
)
